# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyNXLB7B-48JTuaLWBdvyyR3rKbbbpm2
"""

import streamlit as st
from questions import quiz_data

# --- App Configuration ---
st.set_page_config(page_title="NEET Physics Speed-Labs", layout="centered")

# --- Session State (Memory) ---
if 'current_q' not in st.session_state:
    st.session_state.current_q = 0
if 'score' not in st.session_state:
    st.session_state.score = 0
if 'answered' not in st.session_state:
    st.session_state.answered = False

# --- UI Header ---
st.title("⚛️ NEET Physics Speed-Labs")
st.caption("Don't just solve it. Solve it in 30 seconds.")
st.markdown("---")

# --- Game Logic ---
q_index = st.session_state.current_q
if q_index < len(quiz_data):
    data = quiz_data[q_index]

    # Progress Bar
    progress = (q_index / len(quiz_data))
    st.progress(progress, text=f"Question {q_index + 1} of {len(quiz_data)}")

    # Display Question
    st.subheader(f"Topic: {data['topic']}")
    st.latex(data['question'])

    # Options
    choice = st.radio("Select Option:", data['options'], key=f"q{q_index}", index=None)

    # Submit Button
    if st.button("🚀 Lock Answer"):
        if choice:
            st.session_state.answered = True
            if choice == data['correct']:
                st.success("✅ Correct! (+4 Marks)")
                # --- FIX IS HERE (Corrected typo below) ---
                st.session_state.score += 4
            else:
                st.error(f"❌ Wrong! (-1 Mark). Correct answer: {data['correct']}")
                st.session_state.score -= 1
        else:
            st.warning("Please select an option first.")

    # Reveal Tricks & Solutions (Only after answering)
    if st.session_state.answered:
        col1, col2 = st.columns(2)
        with col1:
            with st.expander("💡 View Short Trick (Speed Hack)"):
                st.info(data['trick'])
        with col2:
            with st.expander("📘 Detailed Solution"):
                st.write(data['solution'])

        # Next Button
        if st.button("Next Question ➡️"):
            st.session_state.current_q += 1
            st.session_state.answered = False
            st.rerun()

else:
    # Final Score Screen
    st.balloons()
    st.title("🏁 Test Complete!")
    final_score = st.session_state.score
    st.metric(label="Your NEET Physics Score", value=f"{final_score} / {len(quiz_data)*4}")

    if st.button("Restart Quiz"):
        st.session_state.current_q = 0
        st.session_state.score = 0
        st.session_state.answered = False
        st.rerun()

