# -*- coding: utf-8 -*-
"""question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5-ESymc2oOWcRKO8AJbv6By1-5ZS6ra
"""

# questions.py
quiz_data = [
    {
        "topic": "Kinematics",
        "question": r"A particle is projected at $45^\circ$ with velocity $v$. The ratio of the range to the maximum height ($R/H$) is:",
        "options": ["1", "2", "4", "8"],
        "correct": "4",
        "solution": r"Formula method: $R = \frac{u^2 \sin 2\theta}{g}$ and $H = \frac{u^2 \sin^2 \theta}{2g}$. Divide them: $\frac{R}{H} = \frac{\sin 2\theta}{\sin^2 \theta / 2} = \frac{2 \sin\theta \cos\theta \cdot 2}{\sin^2 \theta} = 4 \cot\theta$. At $45^\circ$, $\cot 45 = 1$, so Ratio = 4.",
        "trick": "Memory Hack: For any projectile, remember the relation $R = 4H \cot \theta$. If angle is $45^\circ$, $\cot 45 = 1$, so directly $R = 4H$."
    },
    {
        "topic": "Laws of Motion",
        "question": r"A block of mass 2kg is suspended by a rope from a lift moving UP with acceleration $2 m/s^2$. Take $g=10 m/s^2$. Tension in rope is:",
        "options": ["16 N", "20 N", "24 N", "28 N"],
        "correct": "24 N",
        "solution": r"Standard method: Draw FBD. $T - mg = ma \Rightarrow T = m(g+a) = 2(10+2) = 24 N$.",
        "trick": "Lift Trick: When independent mass enters a 'G-Force' zone: Moving UP = Heavier ($g_{eff} = g+a$). Moving DOWN = Lighter ($g_{eff} = g-a$). Here UP, so $2 \times (10+2) = 24$."
    },
    {
        "topic": "Work, Energy & Power",
        "question": r"A body moves with velocity $v = k \sqrt{x}$. The work done by net force is proportional to:",
        "options": [r"$x$", r"$x^2$", r"$x^{3/2}$", r"$\sqrt{x}$"],
        "correct": r"$x$",
        "solution": r"Integration method: $a = v \frac{dv}{dx}$. Calculate Force $F=ma$, then Integrate $\int F dx$. Lengthy process.",
        "trick": "Dimensional Hack: Work = Change in KE (Work-Energy Theorem). $KE = \frac{1}{2}mv^2$. Since $v \propto \sqrt{x}$, then $v^2 \propto x$. Therefore, $KE \propto x$, so Work $\propto x$. No calculus needed!"
    }
]

